### ISSUE TITLE
Setup dev environment (ISIS) for autoreduction

### ISSUE THREAD

**Issue by Anders-Markvardsen** [mantidproject/autoreduce#106]
This issue was originally [TRAC 11287](http://trac.mantidproject.org/mantid/ticket/11287)

We have a redhat 6 dev environment, but now our production is windows server 2012 + redhat 7.

Setup windows server 2012 + redhat 7 environment, which a tested can test. 

Where relevant please do not hesitate to update setup documentation.

 - - - - 
Keywords: AUTOREDUCTION

**Comment by cyclohexanamine** [comment]
The front & back end dev servers are both set up fully now, and working. See https://github.com/mantidproject/autoreduce/pull/267. Still not ideal, since the backend dev server seems to be missing some things (script dependencies, etc., such as [here](https://github.com/mantidproject/autoreduce/blob/master/ReductionScripts/isis/merlin/MERLINReduction.py#L7)), so some test cases from the production server don't work in the test environment.
