### ISSUE TITLE
Bug when using same RB numbers but different instruments

### ISSUE THREAD

**Issue by DominicOram** [mantidproject/autoreduce#156]
When a job is submitted on one instrument (e.g. WISH) but has the same RB number as a previously run job on a different instrument (e.g. MAPS) the WebApp has some unexpected behaviour:
* The job will appear under both instruments
* When the job is clicked on for more information (under either instrument) a reduction not found page is displayed

This appears to be purely a Web GUI issue but it may be worth further investigating that everything is working as expected on the backend in this case.

**Comment by abuts** [comment]
I do not think we have the same RB numbers for different instruments and not aware of RB numbers, which would involve more then one instrument, so despite theoretically this is interesting question, it should not happen in practice. 

RB which illustrates this problem is 1410023 and the job in question are sitting in the queue now.
